name: Build and Push Github Package Registry

on:
  push:
    branches:
      - master

jobs:
  build-and-push:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1

    - name: Build Image
      run: |
        npm run build